# Generated by Django 4.0.6 on 2022-08-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contact_number', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
